### ISSUE TITLE
Bot incorrectly reopens issue closed by OP

### ISSUE THREAD

**Issue by j-f1** [probot/no-response#16]
Issue: https://github.com/prettier/prettier/issues/3914

1. A maintainer added the “status:awaiting response” label.
1. The OP commented and closed the issue.
1. **@no-response** removed the label because the OP had replied.
1. **@no-response** reopened the issue (why did this happen?)

**Comment by lee-dohm** [comment]
The behavior is as designed, [described in the README](https://github.com/probot/no-response#issue_comment-event). I agree though that it is less-than-optimal in this specific instance. I suppose an additional check could be applied where if the OP closed the issue then the bot wouldn't reopen it.

**Comment by azz** [comment]
Could we only reopen the issue if the bit was responsible for the most recent close?

**Comment by azz** [comment]
This is [occurring](https://github.com/prettier/prettier/issues/4034) fairly [frequently](https://github.com/prettier/prettier/issues/4014). @lee-dohm would you accept a PR to change the behaviour to my comment above?

**Comment by bkeepers** [comment]
@azz a PR would be great!

**Comment by Evanito** [comment]
I wanted to do this but got snagged up in the API used by the bot and had trouble being able to compare the actor who closed the issue to the name of the bot itself.

Change should go here:

https://github.com/probot/no-response/blob/a32051df0f886df7b931f137287d3391fd2dcbfd/lib/no-response.js#L31
