### ISSUE TITLE
Archive this repository and recommend actions

### ISSUE THREAD

**Issue by gr2m** [probot/no-response#35]
@lee-dohm as part of an overall audit/clean up of the @probot org (https://github.com/probot/probot/issues/1022), I was wondering if you want to move the app to your personal account? If not, I'd recommend we archive the repository and recommend using Actions instead due to the scheduling aspect of it?

**Comment by lee-dohm** [comment]
Thanks for the offer of relocating it. Unfortunately, I'm not going to have time to maintain it, especially given that I've essentially rewritten it as an Action: https://github.com/lee-dohm/no-response. I agree that archiving it is probably the best course of action.
